language: python
python:
  - '3.4'

install:
  - pip install -U pip
  - pip install '.[test]'
  - pip install coveralls

script:
  - (cd test_proj; py.test --cov compiling_loader)

after_success:
  - (cd test_proj; coveralls)
